// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIQO3hGmAJa3oTwcnXk_LrYVcXcXsdcfI',
    appId: '1:487483812580:web:f8916f9f9cc70366241af1',
    messagingSenderId: '487483812580',
    projectId: 'e-commerce-dc01d',
    authDomain: 'e-commerce-dc01d.firebaseapp.com',
    storageBucket: 'e-commerce-dc01d.firebasestorage.app',
    measurementId: 'G-Z6NEWPFW2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0aSxEMWlXQoNZAKkdzvG2bdYtRZv3lzQ',
    appId: '1:487483812580:android:f36b33a07a563fff241af1',
    messagingSenderId: '487483812580',
    projectId: 'e-commerce-dc01d',
    storageBucket: 'e-commerce-dc01d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_eCuYGaVedanRy66fU5wxQw_VxY-hp3U',
    appId: '1:487483812580:ios:2890b4ce7ca472e7241af1',
    messagingSenderId: '487483812580',
    projectId: 'e-commerce-dc01d',
    storageBucket: 'e-commerce-dc01d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_eCuYGaVedanRy66fU5wxQw_VxY-hp3U',
    appId: '1:487483812580:ios:2890b4ce7ca472e7241af1',
    messagingSenderId: '487483812580',
    projectId: 'e-commerce-dc01d',
    storageBucket: 'e-commerce-dc01d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIQO3hGmAJa3oTwcnXk_LrYVcXcXsdcfI',
    appId: '1:487483812580:web:a3c2e668181de1d1241af1',
    messagingSenderId: '487483812580',
    projectId: 'e-commerce-dc01d',
    authDomain: 'e-commerce-dc01d.firebaseapp.com',
    storageBucket: 'e-commerce-dc01d.firebasestorage.app',
    measurementId: 'G-ZQFBRGR7PM',
  );
}
